<?php

function wpcollectivites_champs_acf(){
    //Page de configuration du plugin
    acf_add_options_page([
        'page_title' => __('WP Collectivités'),
        'menu_title' => __('WP Collectivités'),
        'menu_slug' => 'wp-collectivites-options',
        'redirect' => false,
        'position' => '75',
    ]);

    acf_add_local_field_group(array(
        'key' => 'group_6916fe2fd774c',
        'title' => 'WP Collectivités',
        'fields' => array(
            array(
                'key' => 'field_6916fe300ebe7',
                'label' => 'Message d\'alerte',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_6916fe400ebe8',
                'label' => 'Message d\'alerte activé',
                'name' => 'message_alerte_activation',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_6916fe5b0ebe9',
                'label' => 'Zone d\'affichage du message d\'alerte',
                'name' => 'message_alerte_zone_affichage',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'accueil' => 'Page d\'accueil',
                    'partout' => 'Sur tout le site',
                ),
                'default_value' => 'partout',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'allow_in_bindings' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_6916fe900ebea',
                'label' => 'Type d\'affichage',
                'name' => 'message_alerte_type_affichage',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'popup' => 'Pop-up',
                    'bandeau' => 'Bandeau',
                ),
                'default_value' => 'popup',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'allow_in_bindings' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_6916febe0ebeb',
                'label' => 'Début de la période d\'affichage',
                'name' => 'message_alerte_debut_periode_daffichage',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
                'default_to_current_date' => 0,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_691703860ebec',
                'label' => 'Fin de la période d\'affichage',
                'name' => 'message_alerte_fin_periode_affichage',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
                'default_to_current_date' => 0,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_6917095b18452',
                'label' => 'Texte du message d\'alerte',
                'name' => 'message_alerte_texte',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => 3,
                'placeholder' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_69170a6192614',
                'label' => 'Couleur de fond',
                'name' => 'message_alerte_couleur_fond',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
                'enable_opacity' => 0,
                'return_format' => 'string',
                'allow_in_bindings' => 0,
                'show_custom_palette' => 0,
                'show_color_wheel' => 1,
                'custom_palette_source' => '',
                'palette_colors' => '',
            ),
            array(
                'key' => 'field_69170a7692615',
                'label' => 'Couleur du texte',
                'name' => 'message_alerte_couleur_texte',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#FFFFFF',
                'enable_opacity' => 0,
                'return_format' => 'string',
                'allow_in_bindings' => 0,
                'show_custom_palette' => 0,
                'palette_colors' => '',
                'show_color_wheel' => 1,
                'custom_palette_source' => '',
            ),
            array(
                'key' => 'field_6916fe300fhh1',
                'label' => 'Trombinoscope',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_69170a9692615',
                'label' => 'Couleur de fond',
                'name' => 'trombinoscope_couleur_fond',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#FFFFFF',
                'enable_opacity' => 0,
                'return_format' => 'string',
                'allow_in_bindings' => 0,
                'show_custom_palette' => 0,
                'palette_colors' => '',
                'show_color_wheel' => 1,
                'custom_palette_source' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'wp-collectivites-options',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'display_title' => '',
    ));

    //Bloc marché public
    acf_add_local_field_group( array(
        'key' => 'group_68a5e1a570bba',
        'title' => 'Bloc marché public',
        'fields' => array(
            array(
                'key' => 'field_68a5e1a61f863',
                'label' => 'Titre du marché',
                'name' => 'intitule',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_68a5e1d61f864',
                'label' => 'Date de publication',
                'name' => 'date_publication',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
                'default_to_current_date' => 0,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_68a5e1e61f865',
                'label' => 'Date de clôture',
                'name' => 'date_cloture',
                'aria-label' => '',
                'type' => 'date_time_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y à H:i',
                'return_format' => 'U',
                'first_day' => 1,
                'default_to_current_date' => 0,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_68a5edc73b0ff',
                'label' => 'Type de marché',
                'name' => 'type_marche',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_68a5e2071f866',
                'label' => 'Lien vers la plateforme',
                'name' => 'lien',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_68a5e2301f867',
                'label' => 'Profil acheteur',
                'name' => 'profil_acheteur',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_68a5e2371f868',
                'label' => 'Avis complet',
                'name' => 'avis_complet',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/marche-public',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'display_title' => '',
    ));

    //CPT membre de l'équipe municipale
    acf_add_local_field_group( array(
        'key' => 'group_69175308278fc',
        'title' => 'Membre de l\'équipe municipale',
        'fields' => array(
            array(
                'key' => 'field_691753089b26d',
                'label' => 'Fonction',
                'name' => 'fonction',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_691753179b26e',
                'label' => 'Informations supplémentaires',
                'name' => 'informations_supplementaires',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => 'br',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'membre-equipe-muni',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'display_title' => '',
    ) );

    //CPT acte officiel
    acf_add_local_field_group( array(
        'key' => 'group_68e63631c61cd',
        'title' => 'Acte officiel - Informations',
        'fields' => array(
            array(
                'key' => 'field_68e638d4d39c7',
                'label' => 'Date de publication',
                'name' => 'date_publication',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
                'default_to_current_date' => 0,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_68e63952d39c8',
                'label' => 'Date de fin de publication',
                'name' => 'date_fin_publication',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
                'default_to_current_date' => 0,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_6917542e70b30',
                'label' => 'Publié par',
                'name' => 'publie_par',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'membre-equipe-muni',
                ),
                'post_status' => array(
                    0 => 'publish',
                ),
                'taxonomy' => '',
                'return_format' => 'object',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_68e63a66d39cb',
                'label' => 'Fichier',
                'name' => 'fichier',
                'aria-label' => '',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'acte-officiel',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'show_in_rest' => 0,
        'display_title' => '',
    ) );

    //Bloc actes officiels
    acf_add_local_field_group( array(
        'key' => 'group_68e6503a20850',
        'title' => 'Bloc actes officiels',
        'fields' => array(
            array(
                'key' => 'field_68e6503ab82e4',
                'label' => 'Type d\'actes à afficher',
                'name' => 'type_actes',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'type-acte',
                'add_term' => 0,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'id',
                'field_type' => 'radio',
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/actes-officiels',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'display_title' => '',
    ) );

    //Bloc trombinoscope
    acf_add_local_field_group( array(
        'key' => 'group_691add5496850',
        'title' => 'Bloc trombinoscope',
        'fields' => array(
            array(
                'key' => 'field_691add56a1907',
                'label' => 'Membre de l\'équipe municipale à afficher',
                'name' => 'membre_a_afficher',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'membre-equipe-muni',
                ),
                'post_status' => array(
                    0 => 'publish',
                ),
                'taxonomy' => '',
                'return_format' => 'object',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => array(
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/trombinoscope',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'display_title' => '',
    ) );
}
add_action('acf/init', 'wpcollectivites_champs_acf');
