<?php

function wpcollectivites_cpt(){
    //Actes officiels
    register_post_type( 'acte-officiel', array(
        'labels' => array(
            'name' => 'Actes officiels',
            'singular_name' => 'Acte officiel',
            'menu_name' => 'Actes officiels',
            'all_items' => 'Tous les actes officiels',
            'edit_item' => 'Modifier le document',
            'view_item' => 'Voir le document',
            'view_items' => 'Voir les documents',
            'add_new_item' => 'Ajouter un nouveau document',
            'add_new' => 'Ajouter ',
            'new_item' => 'Nouveau document',
            'parent_item_colon' => 'Parent :',
            'search_items' => 'Rechercher',
            'not_found' => 'Aucun acte officiel trouvé',
            'not_found_in_trash' => 'Aucun acte officiel trouvé dans la corbeille',
            'archives' => 'Archives',
            'attributes' => 'Attributs des actes officiels',
            'insert_into_item' => 'Insérer dans l\'acte officiel',
            'uploaded_to_this_item' => 'Téléversé sur cet acte officiel',
            'filter_items_list' => 'Filtrer la liste des actes officiels',
            'filter_by_date' => 'Filtrer les actes officiels par date',
            'items_list_navigation' => 'Navigation dans la liste des actes officiels',
            'items_list' => 'Liste des actes officiels',
            'item_published' => 'Acte acte officiel publié.',
            'item_published_privately' => 'Acte officiel publié en privé.',
            'item_reverted_to_draft' => 'Acte officiel repassé en brouillon.',
            'item_scheduled' => 'Acte officiel planifié.',
            'item_updated' => 'Acte officiel mis à jour.',
            'item_link' => 'Lien de l\'acte officiel',
            'item_link_description' => 'Un lien vers un acte officiel.',
        ),
        'public' => true,
        'publicly_queryable' => false,
        'show_in_rest' => true,
        'rest_base' => 'acte',
        'menu_position' => 21,
        'menu_icon' => 'dashicons-pdf',
        'supports' => ['title'],
        'taxonomies' => array(
            0 => 'type-acte',
        ),
        'rewrite' => array(
            'feeds' => true,
        ),
        'delete_with_user' => false,
    ) );

    //Membres de l'équipe municipale
    register_post_type( 'membre-equipe-muni', array(
        'labels' => array(
            'name' => 'Membres de l\'équipe municipale',
            'singular_name' => 'Membre de l\'équipe municipale',
            'menu_name' => 'Membres de l\'équipe municipale',
            'all_items' => 'Tous les membres de l\'équipe municipale',
            'edit_item' => 'Modifier le membre de l\'équipe municipale',
            'view_item' => 'Voir le membre de l\'équipe municipale',
            'view_items' => 'Voir les membres de l\'équipe municipale',
            'add_new_item' => 'Ajouter un membre de l\'équipe municipale',
            'add_new' => 'Ajouter un membre de l\'équipe municipale',
            'new_item' => 'Nouveau nembre de l\'équipe municipale',
            'parent_item_colon' => 'Membre de l\'équipe municipale parent :',
            'search_items' => 'Rechercher un membre de l\'équipe municipale',
            'not_found' => 'Aucun membre de l\'équipe municipale trouvé',
            'not_found_in_trash' => 'Aucun membre de l\'équipe municipale trouvé dans la corbeille',
            'archives' => 'Archives des membres de l\'équipe municipale',
            'attributes' => 'Attributs des membres de l\'équipe municipale',
            'insert_into_item' => 'Insérer dans le membre de l\'équipe municipale',
            'uploaded_to_this_item' => 'Téléversé sur ce membre de l\'équipe municipale',
            'filter_items_list' => 'Filtrer la liste des membres de l\'équipe municipale',
            'filter_by_date' => 'Filtrer les membres de l\'équipe municipale par date',
            'items_list_navigation' => 'Navigation dans la liste des membres de l\'équipe municipale',
            'items_list' => 'Liste les membres de l\'équipe municipale',
            'item_published' => 'Membre de l\'équipe municipale publié.',
            'item_published_privately' => 'Membre de l\'équipe municipale publié en privé.',
            'item_reverted_to_draft' => 'Membre de l\'équipe municipale repassé en brouillon.',
            'item_scheduled' => 'Membre de l\'équipe municipale planifié.',
            'item_updated' => 'Membre de l\'équipe municipale mis à jour.',
            'item_link' => 'Lien du membre de l\'équipe municipale',
            'item_link_description' => 'Un lien vers un membre de l\'équipe municipale.',
        ),
        'public' => true,
        'show_in_nav_menus' => false,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-businessperson',
        'supports' => array(
            0 => 'title',
            1 => 'thumbnail',
            2 => 'custom-fields',
        ),
        'delete_with_user' => false,
    ) );
}
add_action( 'init', 'wpcollectivites_cpt');

